export const TABS = {
    PRICE_CODES: {key: 'PRICE_CODES', title: 'Price Codes'},
    PRICE_LIST: {key: 'PRICE_LIST', title: 'Item Pricing List'},
    CHANGE_LIST: {key: 'CHANGE_LIST', title: 'Changes'},
};

export const SET_COMPANY = 'SET_COMPANY';
export const SET_PRICELEVEL = 'SET_PRICELEVEL';
export const SET_PRICECODE = 'SET_PRICECODE';
export const SET_NEW_DISCOUNT_MARKUP = 'SET_NEW_DISCOUNT_MARKUP';
export const CLEAR_ERROR = 'CLEAR_ERROR';

export const LOAD_LIST = 'LOAD_LIST';
export const LOAD_LIST_FAILURE = 'LOAD_LIST_FAILURE';
export const RECEIVE_LIST = 'RECEIVE_LIST';

export const LOAD_PRICELEVELS = 'LOAD_PRICELEVELS';
export const LOAD_PRICELEVELS_FAILURE = 'LOAD_PRICELEVELS_FAILURE';
export const RECEIVE_PRICELEVELS = 'RECEIVE_PRICELEVELS';

export const LOAD_PRICELEVEL = 'LOAD_PRICELEVEL';
export const LOAD_PRICELEVEL_FAILURE = 'LOAD_PRICELEVEL_FAILURE';
export const RECEIVE_PRICELEVEL = 'RECEIVE_PRICELEVEL';

export const LOAD_PRICELEVEL_ITEMS = 'LOAD_PRICELEVEL_ITEMS';
export const LOAD_PRICELEVEL_ITEMS_FAILURE = 'LOAD_PRICELEVEL_ITEMS_FAILURE';
export const RECEIVE_PRICELEVEL_ITEMS = 'RECEIVE_PRICELEVEL_ITEMS';

export const LOAD_PRICECODE_ITEMS = 'LOAD_PRICECODE_ITEMS';
export const LOAD_PRICECODE_ITEMS_FAILURE = 'LOAD_PRICECODE_ITEMS_FAILURE';
export const RECEIVE_PRICECODE_ITEMS = 'RECEIVE_PRICECODE_ITEMS';

export const SAVE_PRICELEVEL = 'SAVE_PRICELEVEL';
export const SAVE_PRICELEVEL_FAILURE = 'SAVE_PRICELEVEL_FAILURE';
export const SAVE_PRICELEVEL_SUCCESS = 'SAVE_PRICELEVEL_SUCCESS';

export const LOAD_PRICECODE_LEVELS = 'LOAD_PRICECODE_LEVELS';
export const LOAD_PRICECODE_LEVELS_FAILURE = 'LOAD_PRICECODE_LEVELS_FAILURE';
export const RECEIVE_PRICECODE_LEVELS = 'RECEIVE_PRICECODE_LEVELS';

export const LOAD_PRICECODE_CHANGES = 'LOAD_PRICECODE_CHANGES';
export const LOAD_PRICECODE_CHANGES_FAILURE = 'LOAD_PRICECODE_CHANGES_FAILURE';
export const RECEIVE_PRICECODE_CHANGES = 'RECEIVE_PRICECODE_CHANGES';

export const LOAD_PRICELEVEL_CHANGES = 'LOAD_PRICELEVEL_CHANGES';
export const LOAD_PRICELEVEL_CHANGES_FAILURE = 'LOAD_PRICELEVEL_CHANGES_FAILURE';
export const RECEIVE_PRICELEVEL_CHANGES = 'RECEIVE_PRICELEVEL_CHANGES';

export const SET_ERROR = 'SET_ERROR';
export const DISMISS_ERROR = 'DISMISS_ERROR';
export const SET_TAB = 'SET_TAB';
export const FETCH_CHANGE_LIST = 'FETCH_CHANGE_LIST';
export const FETCH_CHANGE_LIST_FAILURE = 'FETCH_CHANGE_LIST_FAILURE';
export const RECEIVE_CHANGE_LIST = 'RECEIVE_CHANGE_LIST';

export const SET_USER = 'SET_USER';
export const RECEIVE_USERS = 'RECEIVE_USERS';




